//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessAPI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.
        /// </summary>
        internal static string arms {
            get {
                return ResourceManager.GetString("arms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string beginner {
            get {
                return ResourceManager.GetString("beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyfat.
        /// </summary>
        internal static string bodyfat {
            get {
                return ResourceManager.GetString("bodyfat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calves.
        /// </summary>
        internal static string calves {
            get {
                return ResourceManager.GetString("calves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        internal static string cardio {
            get {
                return ResourceManager.GetString("cardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string chest {
            get {
                return ResourceManager.GetString("chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Peaking.
        /// </summary>
        internal static string competitionPeaking {
            get {
                return ResourceManager.GetString("competitionPeaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound.
        /// </summary>
        internal static string compound {
            get {
                return ResourceManager.GetString("compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endurance.
        /// </summary>
        internal static string endurance {
            get {
                return ResourceManager.GetString("endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility.
        /// </summary>
        internal static string flexibility {
            get {
                return ResourceManager.GetString("flexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Endurance.
        /// </summary>
        internal static string gainEndurance {
            get {
                return ResourceManager.GetString("gainEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Muscle.
        /// </summary>
        internal static string gainMuscle {
            get {
                return ResourceManager.GetString("gainMuscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Strenght.
        /// </summary>
        internal static string gainStrenght {
            get {
                return ResourceManager.GetString("gainStrenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Weight.
        /// </summary>
        internal static string gainWeight {
            get {
                return ResourceManager.GetString("gainWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertrophy.
        /// </summary>
        internal static string hypertrophy {
            get {
                return ResourceManager.GetString("hypertrophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        internal static string intermediate {
            get {
                return ResourceManager.GetString("intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation.
        /// </summary>
        internal static string isolation {
            get {
                return ResourceManager.GetString("isolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isometrics.
        /// </summary>
        internal static string isometrics {
            get {
                return ResourceManager.GetString("isometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose Fat.
        /// </summary>
        internal static string loseFat {
            get {
                return ResourceManager.GetString("loseFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose Weight.
        /// </summary>
        internal static string loseWeight {
            get {
                return ResourceManager.GetString("loseWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower.
        /// </summary>
        internal static string lower {
            get {
                return ResourceManager.GetString("lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantain Healthy Lifestyle.
        /// </summary>
        internal static string mantainHealthyLifestyle {
            get {
                return ResourceManager.GetString("mantainHealthyLifestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Preparation.
        /// </summary>
        internal static string physicalPreparation {
            get {
                return ResourceManager.GetString("physicalPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plyometrics.
        /// </summary>
        internal static string plyometrics {
            get {
                return ResourceManager.GetString("plyometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerlifting.
        /// </summary>
        internal static string powerlifting {
            get {
                return ResourceManager.GetString("powerlifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        internal static string shoulders {
            get {
                return ResourceManager.GetString("shoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string strength {
            get {
                return ResourceManager.GetString("strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper.
        /// </summary>
        internal static string upper {
            get {
                return ResourceManager.GetString("upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string waist {
            get {
                return ResourceManager.GetString("waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weightlifting.
        /// </summary>
        internal static string weightlifting {
            get {
                return ResourceManager.GetString("weightlifting", resourceCulture);
            }
        }
    }
}
